### ISSUE TITLE
Uploads files to a folder named '/'

### ISSUE THREAD

**Issue by kilbd** [BetaHuhn/do-spaces-action#142]
👋🏻 Me again. Sorry!

**🐞 Describe the bug**

I updated to **v2** of this action. Uploads are successful, but all files are placed in a folder named '/' instead of at the root of the Space. One interesting effect is that this folder doesn't appear in my Transmit 5 client, but it does appear in the UI in DigitalOcean's Spaces console. Below you can see files uploaded in previous runs alongside the '/' folder.

<img width="334" alt="Screen Shot 2021-05-02 at 10 07 22 PM" src="https://user-images.githubusercontent.com/2053455/116836025-0d808200-ab93-11eb-9789-ff1400238810.png">

**📚 To Reproduce**

I don't set an `out_dir` in my `with` parameters. I noticed the default for `out_dir` is set to '/'.

**💡 Expected behavior**

I expected files and folders to be placed at the root of the Space, and not in a subfolder.

**⚙️ Environment**
 - OS: GitHub Actions, `runs-on: ubuntu-latest`
 - Action version: v2

**Comment by BetaHuhn** [comment]
Hey @kilbd, thanks for reporting this!

This behavior is kind of unexpected. `/` normally indicates the root of something, but it seems DO Spaces uses an empty string as root.

Will fix this ASAP.

**Comment by BetaHuhn** [comment]
Should be fixed in [v2.0.1](https://github.com/BetaHuhn/do-spaces-action/releases/tag/v2.0.1) 🎉
