### ISSUE TITLE
Removed files aren't getting deleted!?

### ISSUE THREAD

**Issue by azuryceo** [BetaHuhn/do-spaces-action#369]
**🐞 Describe the bug**

When you remove a file from the git repository, it should be also deleted from the DigitalOcean space.

**📚 To Reproduce**

Delete any file from the git repository.

**💡 Expected behavior**

Removed file also gets deleted from the DigitalOcean space.

**⚙️ Environment**
 Doesn't matter.

**📋 Additional questions**

Can we disable backing up the .git folder?

**Comment by BetaHuhn** [comment]
The action doesn't sync your files to Spaces, it only uploads the specified files. It can't detect if a file is deleted.

As you can read in the [README](https://github.com/BetaHuhn/do-spaces-action#-introduction), the main purpose of this action is to upload assets or compiled files to be hosted on Spaces. It is meant to upload once and leave the file in spaces for ever (or until they are manually deleted).

If syncing is something you are interested in, please open a [discussion](https://github.com/BetaHuhn/do-spaces-action/discussions/new?category=ideas) explaining how you imagine such a feature to work and why you might need it.

**Comment by laukstein** [comment]
I noticed this issue too and I agree this should be implemented.

**Comment by BetaHuhn** [comment]
Issues are only used for bugs, this is more of a feature request.

Feel free to open a [discussion](https://github.com/BetaHuhn/do-spaces-action/discussions) describing the feature you are looking for and a use case and I am happy to further discuss this :)
